---
title: "Report on the European Music, Society, and Citizenship"
subtitle: "DOI: 10.5281/zenodo.6464900"
author:
- Daniel Antal, CFA, Reprex & University of Amsterdam
- Edwards, James, PhD, Sinus-Institut
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
  word_document: default
  md_document: default
bibliography:
- datascience.bib
- mme.bib
- legalccsi.bib
- antal.bib
- competition.bib
- caselaw.bib
- dcms.bib
- digitalmusicobservatory.bib
- packages.bib
- musicindustry.bib
- musicology.bib
- statisticalmethodology.bib
- datainteroperability.bib
- eulaw.bib
- openscience.bib
- opa.bib
- opendata.bib
- rpackages.bib
- valuation.bib
- valuegap.bib
---

```{r setupdmoeconomypillar, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, out.width = '95%', fig.align = 'center')
library(knitr)
library(here)
here::here()
```

## Abstract

In the last decade, the evidence-based policy movement gained significant traction in Europe as well as globally. Its focus has been to increase the rigour of the evidence generated, to improve the credibility and understandability of evidence created for policy purposes.  As evidence-based policies often rely on scientific evidence, the evidence-based policy movement went hand in hand with the efforts to increase the transparency and reproducibility of scientific research (See: [@manifesto_for_reproducible_science_2017] and in an EU context [@JRC99722; @reproducibility_scientific_results_eu_2020; @progress_open_science_2020].)  

Our [Report on the European Music, Society, and Citizenship](https://zenodo.org/record/6464900#.YlrfC9pBzIU), and its supporting document, [Music, Society, and Citizenship: Novel data collection methods and indicators](https://zenodo.org/record/6464933#.YlriRNpBzIV)^[Music, Society, and Citizenship: Novel data collection methods and indicators [@DMO_methodology_european_music_society]] will follow the Open Policy Analysis Guidelines and the best practices of the European Union's Knowledge For Policy and the [European Open Science Cloud](https://eosc-portal.eu/) portal.

The current version of the _Report on the European Music, Society, and Citizenship [outline]_ is a research planning document that sets out our 9 transparancy criteria following the best practices (Level 3) of the _Open Policy Analysis Guidelines_, and provides some illustrations on how a "live policy document" works with a few reproducible datasets^[Report on the European Music, Society, and Citizenship [outline] [@report_european_music_economy]]. If our Proposal is successful and gets funded, the document will start to contain reused data from 2023, new data from 2024, and can be first read as draft policy document in the summer of 2024. 

## Report Outline
For full reproducibility, following the Open Policy Analysis guidelines, this deliverable is a “live policy document” that will aim to be first useful for the reader in the calendar year 2024, but will integrate data as they appear in the pipeline from the inception of the project (and illustration data at the Proposal Stage). 

The **Report on Music, Society, and Citizenship in Europe** provides a detailed concert and recorded music audience comparison for all EU countries, starting from 2007, showing the participation in music (audience, amateur practices, education), as well as the role of music in social networks. The document covers the entire EU27, with national chapters in countries where we have more detailed data collection: e.g., it includes environmental, social, and governance sustainability country reports for Italy and Bulgaria, with corporate case studies, meeting the criteria set out in the European Green Deal, the Corporate Social Responsibility Directive proposal and the Sustainable Finance Package (further country chapters may be included provided local stakeholders are open to replicating the data collection using our open-source tools). It also analyses the transfer potential of the Italian pilot study to other European music ecosystems, as a new best practice. It is designed to be readable as a stand-alone deliverable, but the data it presents will also be integrated into the Digital Music Observatory (D5.1).

## Open Policy Analysis Requirements (Level 3) {#OPA-requirements}

### Open Output {#OPA-open-output}
1. **Ensure unified output by defining the most appropriate format for the report
before publishing, and justifying changes to format output across reports.** Best practice: A detailed description of output is provided, including a sample output published 
pre-release of final results, using version control within and across reports

2. **Establish a clear link between input and output by displaying how the output changes under different assumptions**. Best practice: An interactive tool allowing for adjusted inputs is provided, and its underlying code shares the same key sections of code behind the analysis section.

### Open Analysis {#OPA-open-analysis}

3. **Provide clear accounts of all methodological procedures in a way that is easily interpreted by an informed reader.** Code is clearly documented into a dynamic document, or
open notebook. No spreadsheets. Our Methodologies are part of our Proposal, and they can be fined as dynamic document on the Github repo [github.com/dataobservatory-eu/report-european-music-economy](https://github.com/dataobservatory-eu/report-european-music-economy), and versions with metadata and DOI of the methodology document on the Zenodo open science repository under the title [Digital Music Observatory](https://zenodo.org/communities/music_observatory/). 

4. **Share raw (or analytic) data and materials in a way that the analysis is reproducible with minimal effort.**

5. **Share an open report that includes clear accounts of all methodological procedures, data, and assumptions.** Best practice: All project components are organized in a selfcontained folder using a Standard File Structure (SFS), and a readme file is included. We place all files with SFS on the European open science repository Zenodo on [zenodo.org/communities/music_observatory/](https://zenodo.org/communities/music_observatory/).

### Open Materials {#OPA-open-materials}
6. **Standardize the file structure so that materials are organized in a way that is accessible to an informed reader.** Best practice: All project components are organized in a selfcontained folder using a Standard File Structure (SFS)---for this project: [github.com/dataobservatory-eu/report-music-society-citizenship](https://github.com/dataobservatory-eu/report-music-society-citizenship); and a readme file is included (for this report, here).

7. **Label and document each input, including data, research, and guesswork.** Best practice: List all inputs, their sources, and provide links or detailed references. We use DublinCore and DataCite mandatory and recommended descriptive metadata to provide not only full bibliographic reference, but also full findability and interoperabilty, and clear reuse conditions.

7. **Ensure that code/spreadsheets are reproducible**. Best practice: _For code:_ Code is easily readable and possible to run with just one click. _Spreadsheets_ are published with the code, and the code re-creates the spreadsheet from the latest data on one click. New runs are placed in the [Digital Music Observatory community space](https://zenodo.org/communities/music_observatory) on Zenodo, like our  [Harmonized Cultural Access & Participation Dataset for Music](https://zenodo.org/record/5917742#.Ylrb2NpBzIU).

9. **Use a version control strategy.** Best practice: All team members use version control software and track changes in a shared project repository. This document is placed in a version controlled repostiory [github.com/dataobservatory-eu/report-european-music-economy](https://github.com/dataobservatory-eu/report-european-music-economy)


# References